### Numpy

수치해석 수학적 처리, 통계 등을 위한 모듈 - Pandas, Matplotlib,SciPy

In [1]:
!pip install numpy

In [3]:
!pip show numpy

Name: numpy
Version: 1.24.2
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: C:\DEV\Langs\Python311\Lib\site-packages
Requires: 
Required-by: contourpy, folium, matplotlib, opencv-python, pandas


In [4]:
!pip install matplotlib

In [5]:
import pandas as pd
import numpy as np

Numpy 사용이유
- python 1,000,000 건 리스트를 만들고 사용처리 - 대략 200ms
- numpy 1,000,000 건 배열 만들고 사용처리 - 대락 20ms(1/10배)

In [7]:
py_list = list(range(1_000_000)) # 100만건 리스트
np_arr = np.arange(1_000_000) # 100만걸 배열

In [8]:
%timeit for _ in range(10): py_list2 = py_list * 3

254 ms ± 7.64 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
%timeit for _ in range(10): np_arr2 = np_arr * 3

11.6 ms ± 166 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Numpy로 배열 생성, 연산
- 파이썬 리스트 +,* 연산 밖에 없음
- 행렬(벡터)연산이 필요하면 Numpy로 형변환 후 처리가능

In [10]:
list1 = [1,2,3]
list2 = [4,5,6]
list1 + list2

[1, 2, 3, 4, 5, 6]

In [11]:
list2 * 3

[4, 5, 6, 4, 5, 6, 4, 5, 6]

In [12]:
list2 - list1

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [13]:
list2 / list1

TypeError: unsupported operand type(s) for /: 'list' and 'list'

numpy 연산

In [14]:
list2 = [4, 5, 6]
np_arr1 = np.array(list2)

In [15]:
np_arr1

array([4, 5, 6])

In [16]:
np_arr2= np.array([[1, 2, 3], [4, 5, 6]])
np_arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np_arr3 = np.array(list1)
np_arr4 = np.array(list2)

In [18]:
np_arr3 + np_arr4

array([5, 7, 9])

In [19]:
np_arr3 * np_arr4

array([ 4, 10, 18])

In [20]:
np_arr4 - np_arr3

array([3, 3, 3])

In [21]:
np_arr4 / np_arr3

array([4. , 2.5, 2. ])

In [22]:
np.zeros(4000)

array([0., 0., 0., ..., 0., 0., 0.])

In [23]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.empty([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
#랜덤은 활용도가 높음
np.random.randn(50)

array([ 0.46791882,  1.04528055,  0.34316892, -2.04214686,  1.36904572,
        0.79345083,  0.11203004,  0.54966615, -0.39271326, -0.71468112,
        1.44669024, -0.85561206,  1.15672189, -1.41390384,  0.38008972,
        0.56387005,  0.37321384,  0.30044777, -0.20546227,  0.1117191 ,
        0.12087935,  1.46037609, -1.08650366,  1.95707083, -1.53352858,
       -2.21686869, -0.71683868,  0.23648492, -0.58593192, -0.063471  ,
       -0.05405961, -0.05889125,  0.11630227,  2.12711508,  0.80739005,
       -0.37834595,  1.5253334 , -1.66068635,  0.7561627 , -0.30395885,
       -0.16421405,  1.28119687,  0.86655522,  0.90276599,  0.918091  ,
       -0.16470188,  1.34022054, -0.98595587,  0.3413781 ,  0.78751786])

In [26]:
np.random.randn(5,4)

array([[-0.89933158,  1.25264262, -1.59341985, -0.66574786],
       [-0.04728273,  0.8393785 , -0.02865838,  1.98205224],
       [ 0.25441316,  0.70716503, -0.66822137, -0.53740206],
       [-0.58644031, -1.0543172 , -1.26586875,  0.1482293 ],
       [ 0.27631831, -0.28645722,  0.42858411, -0.43418851]])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
list(np.arange(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [29]:
(np_arr3 + np_arr4)<9

array([ True,  True, False])

In [30]:
(np_arr3 + np_arr4)==0

array([False, False, False])

### Numpy 속성

In [31]:
# 1차원 배열은 열값이 앞에 나오고
np_arr1.shape

(3,)

In [32]:
# 2차원 부터는 행, 열순
np_arr2.shape

(2, 3)

In [33]:
np_arr2.dtype

dtype('int32')

In [34]:
np_arr2.T.shape

(3, 2)

기타함수

In [35]:
np_arr5 = np.arange(10)
np_arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# 평균
np_arr5.mean()

4.5

In [37]:
# 합계
np_arr5.sum()

45

In [38]:
# 적층형 합계
np_arr5.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [39]:
np_arr6 = np.random.randn(10)
np_arr6

array([ 0.73837094, -0.1306099 ,  1.58457341, -1.60980345, -0.32976159,
        1.94425881, -0.70475104, -1.11130494,  1.83241768, -0.75362152])

In [40]:
np_arr6 = np_arr6 * 10

In [41]:
np_arr6

array([  7.38370938,  -1.30609897,  15.84573405, -16.09803449,
        -3.29761591,  19.44258812,  -7.04751035, -11.11304943,
        18.32417676,  -7.53621519])

In [42]:
# 오름차순 정렬
np_arr6.sort()


In [43]:
np_arr6

array([-16.09803449, -11.11304943,  -7.53621519,  -7.04751035,
        -3.29761591,  -1.30609897,   7.38370938,  15.84573405,
        18.32417676,  19.44258812])

In [44]:
# 내림차순 정렬 - 특이
-np.sort(-np_arr6)

array([ 19.44258812,  18.32417676,  15.84573405,   7.38370938,
        -1.30609897,  -3.29761591,  -7.04751035,  -7.53621519,
       -11.11304943, -16.09803449])